dist: trusty

language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

install:
  - sudo apt-get -qq update
  - sudo apt-get --yes --assume-yes install
                                           build-essential
                                           python python-jinja2 python-pkg-resources cmake
                                           git subversion libsdl-dev
                                           diffstat texinfo gawk chrpath wget cpio
                                           vim zsh bash ninja-build screen sshpass
                                           bc python-git unzip libxml2-utils gcovr
                                           libcurl4-gnutls-dev zlib1g-dev libbz2-dev
                                           bsdiff libssl-dev autoconf automake
  - sudo apt-get --yes --assume-yes install
                                           expect-dev openjdk-8-jdk gcovr
  - sudo wget -O /usr/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
  - sudo chmod +x /usr/bin/repo
  - git config --global color.ui false
  - git config --global user.name "Travis"
  - git config --global user.email "legato@travis-ci.org"

script:
  - if [ "$CC" == "clang" ]; then export USE_CLANG=1 && which clang; fi
  - cd ..
  - mkdir workspace
  - cd workspace
  - if [ -n "$TRAVIS_TAG" ]; then
       repo init -q -u git://github.com/legatoproject/manifest -m legato/releases/$TRAVIS_TAG.xml ;
    else
       repo init -q -u git://github.com/legatoproject/manifest -m legato/branches/$TRAVIS_BRANCH.xml ;
    fi
  - repo sync
  - cd legato
  - git remote add local ../../legato-af
  - git fetch local HEAD
  - git reset --hard FETCH_HEAD
  - repo forall -c 'echo -n "$REPO_PATH " && git rev-parse HEAD 2>/dev/null'
  - make localhost
