dist: trusty

language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

install:
  - sudo apt-get -qq update
  - sudo apt-get --yes --assume-yes install vim expect-dev build-essential
    fakeroot sed git-core gawk unzip wget diffstat python python-jinja2
    python-pip python-pyparsing python-pysqlite2 cmake coreutils curl
    bison flex chrpath libgmp3-dev libmpfr-dev libreadline6-dev libtool libxml2-dev
    libxml-libxml-perl m4 ninja-build autoconf pkg-config doxygen graphviz gcovr
    libbz2-dev bsdiff libcurl4-gnutls-dev zlib1g-dev
  - sudo wget -O /usr/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
  - sudo chmod +x /usr/bin/repo
  - git config --global color.ui false
  - git config --global user.name "Travis"
  - git config --global user.email "legato@travis-ci.org"

script:
  - if [ "$CC" == "clang" ]; then export USE_CLANG=1 && which clang; fi
  - cd ..
  - mkdir workspace
  - cd workspace
  - repo init -q -u git://github.com/legatoproject/manifest
  - repo sync
  - cd legato
  - git remote add local ../../legato-af
  - git fetch local
  - git reset --hard FETCH_HEAD
  - make localhost
